apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-infra-455809
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/matheoberger/ArgoCD.git
    targetRevision: HEAD
    path: dev

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  
    automated:
      selfHeal: true
      prune: true